-- Sep 18, 2013 12:11:46 PM VET
-- LVE-Import
ALTER TABLE I_BPartner ADD COLUMN BP_Birthday TIMESTAMP DEFAULT NULL 
;

-- Sep 18, 2013 12:12:01 PM VET
-- LVE-Import
ALTER TABLE I_BPartner ADD COLUMN Degree VARCHAR(2) DEFAULT NULL 
;

-- Sep 18, 2013 12:12:08 PM VET
-- LVE-Import
ALTER TABLE I_BPartner ADD COLUMN EmployeeStatus VARCHAR(2) DEFAULT NULL 
;

-- Sep 18, 2013 12:12:13 PM VET
-- LVE-Import
ALTER TABLE I_BPartner ADD COLUMN Gender CHAR(1) DEFAULT NULL 
;

-- Sep 18, 2013 12:12:19 PM VET
-- LVE-Import
ALTER TABLE I_BPartner ADD COLUMN IsCAPTA CHAR(1) DEFAULT NULL CHECK (IsCAPTA IN ('Y','N'))
;

-- Sep 18, 2013 12:12:24 PM VET
-- LVE-Import
ALTER TABLE I_BPartner ADD COLUMN IsDepending CHAR(1) DEFAULT NULL CHECK (IsDepending IN ('Y','N'))
;

-- Sep 18, 2013 12:12:30 PM VET
-- LVE-Import
ALTER TABLE I_BPartner ADD COLUMN IsGrowthPlan CHAR(1) DEFAULT NULL CHECK (IsGrowthPlan IN ('Y','N'))
;

-- Sep 18, 2013 12:12:36 PM VET
-- LVE-Import
ALTER TABLE I_BPartner ADD COLUMN IsJubilate CHAR(1) DEFAULT NULL CHECK (IsJubilate IN ('Y','N'))
;

-- Sep 18, 2013 12:12:40 PM VET
-- LVE-Import
ALTER TABLE I_BPartner ADD COLUMN IsScholarship CHAR(1) DEFAULT NULL CHECK (IsScholarship IN ('Y','N'))
;

-- Sep 18, 2013 12:12:46 PM VET
-- LVE-Import
ALTER TABLE I_BPartner ADD COLUMN IsUnionized CHAR(1) DEFAULT NULL CHECK (IsUnionized IN ('Y','N'))
;

-- Sep 18, 2013 12:12:52 PM VET
-- LVE-Import
ALTER TABLE I_BPartner ADD COLUMN Relationship VARCHAR(2) DEFAULT NULL 
;

-- Sep 18, 2013 12:12:58 PM VET
-- LVE-Import
ALTER TABLE I_BPartner ADD COLUMN Turn VARCHAR(2) DEFAULT NULL 
;

