-- 8/07/2014 07:58:36 PM CEST
-- LVE-HR
CREATE TABLE LVE_HR_DependentConcept (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, ColumnType CHAR(1) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DependentConcept_ID NUMERIC(10) NOT NULL, FormatPattern VARCHAR(22) DEFAULT NULL , HR_Concept_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_HR_DependentConcept_ID NUMERIC(10) NOT NULL, Prefix VARCHAR(60) DEFAULT NULL , SeqNo NUMERIC(10) DEFAULT NULL , Suffix VARCHAR(60) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT LVE_HR_DependentConcept_Key PRIMARY KEY (LVE_HR_DependentConcept_ID))
;

-- 8/07/2014 07:58:45 PM CEST
-- LVE-HR
CREATE TABLE LVE_HR_LoanDefinition (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, C_Tax_ID NUMERIC(10) DEFAULT NULL , Description VARCHAR(255) DEFAULT NULL , Interest_A_Concept_ID NUMERIC(10) DEFAULT NULL , Interest_C_Concept_ID NUMERIC(10) DEFAULT NULL , Interest_D_Concept_ID NUMERIC(10) DEFAULT NULL , Interest_DM_Concept_ID NUMERIC(10) DEFAULT NULL , Interest_R_Concept_ID NUMERIC(10) DEFAULT NULL , Interest_T_Concept_ID NUMERIC(10) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Loan_A_Concept_ID NUMERIC(10) DEFAULT NULL , Loan_C_Concept_ID NUMERIC(10) DEFAULT NULL , Loan_D_Concept_ID NUMERIC(10) DEFAULT NULL , Loan_F_Concept_ID NUMERIC(10) DEFAULT NULL , Loan_I_Concept_ID NUMERIC(10) DEFAULT NULL , Loan_P_Concept_ID NUMERIC(10) DEFAULT NULL , Loan_T_Concept_ID NUMERIC(10) DEFAULT NULL , LVE_HR_LoanDefinition_ID NUMERIC(10) NOT NULL, ManagesInterest CHAR(1) CHECK (ManagesInterest IN ('Y','N')) NOT NULL, Name VARCHAR(60) NOT NULL, Processed CHAR(1) DEFAULT NULL CHECK (Processed IN ('Y','N')), Processing CHAR(1) DEFAULT NULL , Tax_C_Concept_ID NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) NOT NULL, CONSTRAINT LVE_HR_LoanDefinition_Key PRIMARY KEY (LVE_HR_LoanDefinition_ID))
;

-- 8/07/2014 07:58:54 PM CEST
-- LVE-HR
CREATE TABLE LVE_HR_P_Combination (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_BPartner_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , HR_Department_ID NUMERIC(10) DEFAULT NULL , HR_Job_ID NUMERIC(10) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_HR_P_Combination_ID NUMERIC(10) NOT NULL, LVE_HR_Provision_ID NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT LVE_HR_P_Combination_Key PRIMARY KEY (LVE_HR_P_Combination_ID))
;

-- 8/07/2014 07:59:05 PM CEST
-- LVE-HR
CREATE TABLE LVE_HR_ProcessReport (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsOrderBy CHAR(1) DEFAULT 'Y' CHECK (IsOrderBy IN ('Y','N')), LVE_HR_ProcessReport_ID NUMERIC(10) NOT NULL, Name VARCHAR(60) NOT NULL, PrintName VARCHAR(60) DEFAULT NULL , Processing CHAR(1) DEFAULT NULL , ReceiptFooterMsg VARCHAR(255) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT LVE_HR_ProcessReport_Key PRIMARY KEY (LVE_HR_ProcessReport_ID))
;

-- 8/07/2014 07:59:13 PM CEST
-- LVE-HR
CREATE TABLE LVE_HR_ProcessReportLine (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, HR_Concept_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_HR_ProcessReport_ID NUMERIC(10) NOT NULL, LVE_HR_ProcessReportLine_ID NUMERIC(10) NOT NULL, PrintName VARCHAR(60) DEFAULT NULL , SeqNo NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT LVE_HR_ProcessReportLine_Key PRIMARY KEY (LVE_HR_ProcessReportLine_ID))
;

-- 8/07/2014 07:59:22 PM CEST
-- LVE-HR
CREATE TABLE LVE_HR_Provision (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_HR_Provision_ID NUMERIC(10) NOT NULL, LVE_HR_ProvisionType_ID NUMERIC(10) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) NOT NULL, CONSTRAINT LVE_HR_Provision_Key PRIMARY KEY (LVE_HR_Provision_ID))
;

-- 8/07/2014 07:59:33 PM CEST
-- LVE-HR
CREATE TABLE LVE_HR_ProvisionType (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_HR_ProvisionType_ID NUMERIC(10) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) NOT NULL, CONSTRAINT LVE_HR_ProvisionType_Key PRIMARY KEY (LVE_HR_ProvisionType_ID))
;

-- Sep 14, 2013 12:43:47 PM VET
-- LVE-HR
ALTER TABLE HR_Employee ADD COLUMN IsCAPTA CHAR(1) DEFAULT NULL CHECK (IsCAPTA IN ('Y','N'))
;

-- Sep 14, 2013 12:43:55 PM VET
-- LVE-HR
ALTER TABLE HR_Employee ADD COLUMN IsGrowthPlan CHAR(1) DEFAULT NULL CHECK (IsGrowthPlan IN ('Y','N'))
;

-- Sep 14, 2013 12:44:01 PM VET
-- LVE-HR
ALTER TABLE HR_Employee ADD COLUMN IsJubilate CHAR(1) DEFAULT NULL CHECK (IsJubilate IN ('Y','N'))
;

-- Sep 14, 2013 12:44:06 PM VET
-- LVE-HR
ALTER TABLE HR_Employee ADD COLUMN IsUnionized CHAR(1) DEFAULT NULL CHECK (IsUnionized IN ('Y','N'))
;

-- 04/02/2014 10:57:51 AM CET
-- LVE-HR
ALTER TABLE HR_Employee ADD COLUMN SSDiscountRate NUMERIC DEFAULT NULL 
;

-- May 25, 2014 12:10:47 AM VET
-- LVE HR
ALTER TABLE HR_Employee ADD COLUMN IsHCM CHAR(1) DEFAULT 'N' CHECK (IsHCM IN ('Y','N'))
;

-- May 25, 2014 12:14:24 AM VET
-- LVE HR
ALTER TABLE HR_Payroll ADD COLUMN CopyFrom CHAR(1) DEFAULT NULL 
;

-- May 25, 2014 12:14:56 AM VET
-- LVE HR
ALTER TABLE HR_Payroll ADD COLUMN HR_Concept_ID NUMERIC(10) DEFAULT NULL 
;

-- May 25, 2014 12:37:51 AM VET
-- LVE HR
ALTER TABLE C_BankAccount ADD COLUMN PaymentExportClassHR VARCHAR(60) DEFAULT NULL 
;

-- 7/07/2014 11:36:17 PM CEST
-- LVE-HR
ALTER TABLE AD_User ADD COLUMN IsActiveStudent CHAR(1) DEFAULT 'N' CHECK (IsActiveStudent IN ('Y','N'))
;

-- 9/07/2014 10:23:51 PM CEST
-- LVE-HR
ALTER TABLE LVE_HR_Provision ADD COLUMN M_Product_ID NUMERIC(10) DEFAULT NULL 
;

-- 9/07/2014 10:25:59 PM CEST
-- LVE-HR
ALTER TABLE LVE_HR_P_Combination ADD COLUMN LVE_HR_ProvisionType_ID NUMERIC(10) DEFAULT NULL 
;

-- 9/07/2014 10:26:27 PM CEST
-- LVE-HR
ALTER TABLE LVE_HR_P_Combination ADD COLUMN HR_Payroll_ID NUMERIC(10) DEFAULT NULL 
;

-- 9/07/2014 10:27:22 PM CEST
-- LVE-HR
ALTER TABLE LVE_HR_P_Combination ALTER COLUMN LVE_HR_Provision_ID DROP NOT NULL
;

-- 9/07/2014 10:27:22 PM CEST
-- LVE-HR
ALTER TABLE LVE_HR_P_Combination ALTER COLUMN LVE_HR_Provision_ID SET DEFAULT NULL
;

-- 14/07/2014 11:48:43 AM CEST
-- LVE-HR
ALTER TABLE LVE_HR_P_Combination ADD COLUMN Qty NUMERIC DEFAULT '1' NOT NULL
;

-- 14/07/2014 11:49:24 AM CEST
-- LVE-HR
ALTER TABLE LVE_HR_ProcessReport ADD COLUMN AD_PrintFormat_ID NUMERIC(10) DEFAULT NULL 
;

-- 14/07/2014 03:57:33 PM CEST
-- LVE-HR
ALTER TABLE LVE_HR_Provision ADD COLUMN Type CHAR(1) DEFAULT 'H' NOT NULL
;

-- Add Changes in Tables 2014-07-14

-- 14/07/2014 10:48:57 PM CEST
-- LVE-HR
CREATE TABLE LVE_HR_SchoolInstitution (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_HR_SchoolInstitution_ID NUMERIC(10) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) NOT NULL, CONSTRAINT LVE_HR_SchoolInstitution_Key PRIMARY KEY (LVE_HR_SchoolInstitution_ID))
;

-- 14/07/2014 10:49:29 PM CEST
-- LVE-HR
CREATE TABLE LVE_HR_PathologyType (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_HR_PathologyType_ID NUMERIC(10) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) NOT NULL, CONSTRAINT LVE_HR_PathologyType_Key PRIMARY KEY (LVE_HR_PathologyType_ID))
;

-- 14/07/2014 10:49:48 PM CEST
-- LVE-HR
CREATE TABLE LVE_HR_Pathology (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_HR_Pathology_ID NUMERIC(10) NOT NULL, LVE_HR_PathologyType_ID NUMERIC(10) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) NOT NULL, CONSTRAINT LVE_HR_Pathology_Key PRIMARY KEY (LVE_HR_Pathology_ID))
;

-- 14/07/2014 10:50:03 PM CEST
-- LVE-HR
CREATE TABLE LVE_HR_BPPathology (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_BPartner_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_HR_BPPathology_ID NUMERIC(10) NOT NULL, LVE_HR_Pathology_ID NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT LVE_HR_BPPathology_Key PRIMARY KEY (LVE_HR_BPPathology_ID))
;

-- 14/07/2014 10:50:27 PM CEST
-- LVE-HR
CREATE TABLE LVE_HR_BPMeasures (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_BPartner_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, C_UOM_ID NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_HR_BPMeasures_ID NUMERIC(10) NOT NULL, Type CHAR(1) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT LVE_HR_BPMeasures_Key PRIMARY KEY (LVE_HR_BPMeasures_ID))
;

-- 14/07/2014 10:50:57 PM CEST
-- LVE-HR
ALTER TABLE C_BPartner ADD COLUMN IsSpecialCondition CHAR(1) DEFAULT 'N' CHECK (IsSpecialCondition IN ('Y','N'))
;

-- 14/07/2014 10:51:11 PM CEST
-- LVE-HR
ALTER TABLE C_BPartner ADD COLUMN LVE_HR_SchoolInstitution_ID NUMERIC(10) DEFAULT NULL 
;

-- 9/07/2014 10:27:22 PM CEST
-- LVE-HR
ALTER TABLE LVE_HR_P_Combination ALTER COLUMN LVE_HR_ProvisionType_ID SET NOT NULL
;

-- 17/07/2014 06:05:51 PM CEST
-- LVE-HR
ALTER TABLE C_BPartner ADD COLUMN Degree VARCHAR(2) DEFAULT NULL 
;

-- 17/07/2014 06:06:02 PM CEST
-- LVE-HR
ALTER TABLE C_BPartner ADD COLUMN IsMilitaryLicense CHAR(1) DEFAULT 'N' CHECK (IsMilitaryLicense IN ('Y','N'))
;

-- 17/07/2014 06:22:01 PM CEST
-- LVE-HR
ALTER TABLE C_BP_BankAccount ADD COLUMN IsPayrollAccount CHAR(1) DEFAULT 'N' CHECK (IsPayrollAccount IN ('Y','N'))
;

-- Jul 18, 2014 3:16:27 PM VET
-- LVE HR
ALTER TABLE HR_Payroll ADD COLUMN IsNotRegularPayroll CHAR(1) DEFAULT NULL CHECK (IsNotRegularPayroll IN ('Y','N'))
;

-- 23/07/2014 11:01:10 AM CEST
-- LVE-HR
ALTER TABLE C_BPartner ADD COLUMN IsUniqueForProvision CHAR(1) DEFAULT 'N' CHECK (IsUniqueForProvision IN ('Y','N'))
;

-- 23/07/2014 11:01:31 AM CEST
-- LVE-HR
ALTER TABLE HR_Job ADD COLUMN IsUniqueForProvision CHAR(1) DEFAULT 'N' CHECK (IsUniqueForProvision IN ('Y','N'))
;

-- 23/07/2014 11:01:49 AM CEST
-- LVE-HR
ALTER TABLE HR_Department ADD COLUMN IsUniqueForProvision CHAR(1) DEFAULT 'N' CHECK (IsUniqueForProvision IN ('Y','N'))
;

-- 24/07/2014 12:14:44 PM CEST
-- LVE-HR
ALTER TABLE LVE_HR_ProcessReport ADD COLUMN FileExportClass VARCHAR(60) DEFAULT NULL 
;

-- 25/07/2014 10:00:32 AM CEST
-- LVE-HR
ALTER TABLE LVE_HR_ProcessReport ADD COLUMN IsFileExport CHAR(1) DEFAULT 'N' CHECK (IsFileExport IN ('Y','N'))
;

-- 12/08/2014 10:08:05 PM CEST
-- LVE-HR
ALTER TABLE HR_PaySelection ADD COLUMN IsValid CHAR(1) DEFAULT 'Y' 
;

-- Aug 15, 2014 2:41:25 PM UTC
-- LVE HR
CREATE TABLE LVE_HR_DegreeInstruction (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_HR_DegreeInstruction_ID NUMERIC(10) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) DEFAULT NULL , CONSTRAINT LVE_HR_DegreeInstruction_Key PRIMARY KEY (LVE_HR_DegreeInstruction_ID))
;

-- Aug 15, 2014 2:41:33 PM UTC
-- LVE HR
CREATE TABLE LVE_HR_DM_Combination (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_BPartner_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_HR_DegreeInstruction_ID NUMERIC(10) NOT NULL, LVE_HR_Mention_ID NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT LVE_HR_DM_Combination_Key PRIMARY KEY (LVE_HR_Mention_ID))
;

-- Aug 15, 2014 2:41:40 PM UTC
-- LVE HR
CREATE TABLE LVE_HR_Mention (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_HR_DegreeInstruction_ID NUMERIC(10) NOT NULL, LVE_HR_Mention_ID NUMERIC(10) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) DEFAULT NULL , CONSTRAINT LVE_HR_Mention_Key PRIMARY KEY (LVE_HR_Mention_ID))
;

-- Aug 15, 2014 3:24:53 PM UTC
-- LVE HR
ALTER TABLE C_BPartner ADD COLUMN BirthPlace_ID NUMERIC(10) DEFAULT NULL 
;

-- Aug 15, 2014 3:25:08 PM UTC
-- LVE HR
ALTER TABLE AD_Org ADD COLUMN SSDiscountRate NUMERIC DEFAULT '0' 
;

-- 18/08/2014 09:51:09 AM UTC
-- LVE HR
CREATE TABLE T_SalaryChange (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_PInstance_ID NUMERIC(10) DEFAULT NULL , Amount NUMERIC DEFAULT NULL , DateTrx TIMESTAMP DEFAULT NULL , HR_Employee_ID NUMERIC(10) DEFAULT NULL , IsSimulation CHAR(1) DEFAULT NULL CHECK (IsSimulation IN ('Y','N')), NewSalary NUMERIC DEFAULT NULL , Percentage NUMERIC DEFAULT NULL , PreviousSalary NUMERIC DEFAULT NULL , Qty NUMERIC DEFAULT NULL , ServiceDate TIMESTAMP DEFAULT NULL , TextMsg VARCHAR(2000) DEFAULT NULL )
;

-- Aug 22, 2014 4:16:25 AM VET
-- LVE HR
ALTER TABLE T_SalaryChange ADD COLUMN HR_Concept_ID NUMERIC(10) DEFAULT NULL 
;

-- Aug 22, 2014 4:17:26 AM VET
-- LVE HR
ALTER TABLE T_SalaryChange ADD COLUMN ValidConcept_ID NUMERIC(10) DEFAULT NULL 
;

-- Aug 25, 2014 5:25:58 PM VET
-- LVE HR
ALTER TABLE T_SalaryChange ADD COLUMN Description VARCHAR(255) DEFAULT NULL 
;

-- Oct 16, 2014 3:29:41 PM VET
-- LVE-HR
ALTER TABLE AD_Org ADD COLUMN SSClientDiscountRate NUMERIC DEFAULT NULL 
;


-- Oct 16, 2014 3:30:43 PM VET
-- LVE-HR
ALTER TABLE LVE_HR_LoanDefinition ADD COLUMN Interest_ND_Concept_ID NUMERIC(10) DEFAULT NULL 
;

-- Oct 16, 2014 3:32:55 PM VET
-- LVE-HR
ALTER TABLE LVE_HR_LoanDefinition ADD COLUMN Loan_I_SP_Concept_ID NUMERIC(10) DEFAULT NULL 
;

-- 14/01/2015 09:52:56 AM CET
-- LVE-HR
ALTER TABLE LVE_HR_LoanDefinition ADD COLUMN Interest_NDT_Concept_ID NUMERIC(10) DEFAULT NULL 
;

-- 14/01/2015 09:53:04 AM CET
-- LVE-HR
ALTER TABLE LVE_HR_LoanDefinition ADD COLUMN Interest_PB_Concept_ID NUMERIC(10) DEFAULT NULL 
;

-- 14/01/2015 09:53:12 AM CET
-- LVE-HR
ALTER TABLE LVE_HR_LoanDefinition ADD COLUMN Interest_TI_Concept_ID NUMERIC(10) DEFAULT NULL 
;

-- 14/01/2015 09:53:22 AM CET
-- LVE-HR
ALTER TABLE LVE_HR_LoanDefinition ADD COLUMN Interest_TT_Concept_ID NUMERIC(10) DEFAULT NULL 
;

-- Jan 19, 2015 11:48:32 AM EST
-- HR Loan
CREATE TABLE LVE_HR_Loan (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Amt NUMERIC NOT NULL, C_BPartner_ID NUMERIC(10) NOT NULL, C_DocType_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'PR' NOT NULL, DocStatus VARCHAR(2) DEFAULT 'DR' NOT NULL, DocumentNo VARCHAR(30) DEFAULT NULL , HR_Process_ID NUMERIC(10) DEFAULT NULL , InterestAmt NUMERIC DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT NULL CHECK (IsApproved IN ('Y','N')), LVE_HR_LoanDefinition_ID NUMERIC(10) NOT NULL, LVE_HR_Loan_ID NUMERIC(10) NOT NULL, PaymentRule CHAR(1) DEFAULT 'A' NOT NULL, Processed CHAR(1) DEFAULT 'N' CHECK (Processed IN ('Y','N')) NOT NULL, Processing CHAR(1) DEFAULT NULL , TaxAmt NUMERIC DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT LVE_HR_Loan_Key PRIMARY KEY (LVE_HR_Loan_ID))
;

-- 18/01/2015 05:14:38 PM EST
-- HR Loan
CREATE TABLE LVE_HR_LoanPaymentTerm (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Amt NUMERIC NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, HR_Payroll_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_HR_Loan_ID NUMERIC(10) NOT NULL, LVE_HR_LoanPaymentTerm_ID NUMERIC(10) NOT NULL, Processed CHAR(1) DEFAULT 'N' CHECK (Processed IN ('Y','N')) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, ValidFrom TIMESTAMP NOT NULL, ValidTo TIMESTAMP DEFAULT NULL , CONSTRAINT LVE_HR_LoanPaymentTerm_Key PRIMARY KEY (LVE_HR_LoanPaymentTerm_ID))
;

-- Jan 19, 2015 6:22:51 PM EST
-- HR Loan
CREATE TABLE LVE_HR_LoanAmortization (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Amt NUMERIC NOT NULL, Balance NUMERIC NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, InterestAmt NUMERIC DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_HR_LoanAmortization_ID NUMERIC(10) NOT NULL, LVE_HR_Loan_ID NUMERIC(10) NOT NULL, Processed CHAR(1) DEFAULT 'N' CHECK (Processed IN ('Y','N')) NOT NULL, SeqNo NUMERIC(10) DEFAULT NULL , TaxAmt NUMERIC DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT LVE_HR_LoanAmortization_Key PRIMARY KEY (LVE_HR_LoanAmortization_ID))
;


-- Aug 29, 2014 5:59:31 PM VET
-- LVE HR
ALTER TABLE LVE_HR_DM_Combination ADD COLUMN DateFrom TIMESTAMP DEFAULT NULL 
;

-- Aug 29, 2014 5:59:38 PM VET
-- LVE HR
ALTER TABLE LVE_HR_DM_Combination ADD COLUMN DateTo TIMESTAMP DEFAULT NULL 
;
