-- 30/08/2013 11:46:26 AM VET
-- Order Prepay
ALTER TABLE C_Order ADD COLUMN IsPayScheduleValid CHAR(1) DEFAULT 'N' CHECK (IsPayScheduleValid IN ('Y','N'))
;

-- Oct 2, 2014 3:07:18 PM VET
-- LVE-OrderPrepaySchedule
ALTER TABLE C_PaymentTerm ADD COLUMN IsLineAmtBased CHAR(1) DEFAULT 'N' CHECK (IsLineAmtBased IN ('Y','N'))
;

-- 21/07/2014 11:33:09 AM VET
-- LVE-EFT
ALTER TABLE C_DocType ADD COLUMN RequestType VARCHAR(4) DEFAULT NULL 
;

-- Jul 22, 2014 9:14:33 AM VET
-- LVE EFT
ALTER TABLE C_PaySelectionLine ADD COLUMN C_Order_ID NUMERIC(10) DEFAULT NULL 
;

-- Jul 22, 2014 9:14:43 AM VET
-- LVE EFT
ALTER TABLE C_PaySelectionLine ADD COLUMN LVE_PaymentRequest_ID NUMERIC(10) DEFAULT NULL 
;

-- Jul 22, 2014 11:49:22 AM VET
-- LVE EFT
ALTER TABLE C_PaySelectionLine ADD COLUMN GL_JournalLine_ID NUMERIC(10) DEFAULT NULL 
;

-- Jul 29, 2014 9:59:38 PM VET
-- LVE EFT
ALTER TABLE C_PaySelectionLine ALTER COLUMN C_Invoice_ID DROP NOT NULL
;

-- Oct 14, 2014 3:29:42 PM VET
-- LVE-EFT
ALTER TABLE C_BP_BankAccount ADD COLUMN IsDefault CHAR(1) DEFAULT 'N' CHECK (IsDefault IN ('Y','N'))
;

-- Oct 14, 2014 3:29:55 PM VET
-- LVE-EFT
ALTER TABLE C_BP_BankAccount ADD COLUMN PaymentRule CHAR(1) DEFAULT NULL 
;

-- Oct 14, 2014 11:11:18 PM VET
-- LVE-EFT
ALTER TABLE C_PaySelectionLine ADD COLUMN C_BPartner_ID NUMERIC(10) DEFAULT NULL 
;

-- Oct 14, 2014 11:11:48 PM VET
-- LVE-EFT
ALTER TABLE C_PaySelectionLine ADD COLUMN LVE_PaymentRequestLine_ID NUMERIC(10) DEFAULT NULL 
;

-- Oct 14, 2014 11:11:55 PM VET
-- LVE-EFT
ALTER TABLE C_PaySelectionLine ADD COLUMN RequestType VARCHAR(4) DEFAULT NULL 
;

